version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/neonadeuli
    volumes:
      - .:/app/backend
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=neonadeuli
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: