version: '3.8'

services:
  postgresql:
    container_name: neonadeuli-postgresql
    image: postgres:13
    restart: unless-stopped
    environment:
      - POSTGRES_DB=neonadeuli
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d neonadeuli"]
      interval: 10s
      timeout: 4s
      retries: 5
      start_period: 30s
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: neonadeuli-redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
  redis_data:
