name: Close Associated Issue and Link PR

on:
  pull_request:
    types: [closed]
    branches:
      - develop
      - 'feature/**'
      - 'hotfix/**'

jobs:
  close-issue-and-link:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
    - name: Close associated issue and link PR
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const pr = context.payload.pull_request;
          const prBody = pr.body;
          
          const issueRefs = prBody.match(/(close|closes|closed|fix|fixes|fixed|resolve|resolves|resolved)\s+#(\d+)/gi);
          
          if (issueRefs) {
            for (const ref of issueRefs) {
              const issueNumber = ref.match(/#(\d+)/)[1];
              
              try {
                // 이슈 닫기
                await github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issueNumber,
                  state: 'closed'
                });
                
                // PR에 라벨 추가
                await github.rest.issues.addLabels({
                  issue_number: pr.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  labels: [`closed-issue-${issueNumber}`]
                });
                
                // 이슈에 PR 링크 추가
                await github.rest.issues.createComment({
                  issue_number: issueNumber,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: `This issue was closed by PR #${pr.number}`
                });
                
                console.log(`Closed Issue #${issueNumber} and linked to PR #${pr.number}`);
              } catch (error) {
                console.error(`Error processing Issue #${issueNumber}: ${error}`);
              }
            }
          } else {
            console.log('No issue references found in PR description');
          }